# Generated by Django 4.2.6 on 2023-10-28 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora_page', '0005_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
